# Generated by Django 3.1.7 on 2021-03-04 11:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFromShopee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.TextField(max_length=255)),
                ('title', models.TextField(max_length=255)),
                ('supplier', models.TextField(max_length=255)),
                ('description', models.TextField()),  # Removed max_length for longer descriptions
                ('brand', models.TextField(max_length=255)),
                ('price', models.DecimalField(max_digits=12, decimal_places=2)),  # Changed to DecimalField for price
                ('img_urls', django.contrib.postgres.fields.ArrayField(
                    base_field=models.TextField(), blank=True, size=None)),  # Changed to TextField to store URLs
                ('variants', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('categories', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
    ]