# Generated by Django 3.0.11 on 2021-01-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=False, default='Description not provided'),  # Enforcing non-null with a default value
        ),
    ]
