# Generated by Django 3.0.11 on 2021-01-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_product_category'),
    ]

    operations = [
        # This migration removes the 'category' field from the Product model.
        # The field was later reintroduced in a subsequent migration (see 0014...).
        # It is kept for consistency in the migration history.
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
