# Generated by Django 3.0.11 on 2021-01-10 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_product_category'),
    ]

    operations = [
        # This migration deletes the 'Category' model.
        # Ensure this deletion aligns with the current database schema,
        # and that any related models or fields (e.g., Product) have been adjusted accordingly.
        migrations.DeleteModel(
            name='Category',
        ),
    ]
