# Generated by Django 3.1.4 on 2021-02-20 09:12

from django.db import migrations, models
import os
import binascii


def generate_salt():
    return binascii.hexlify(os.urandom(16)).decode()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210218_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='salt',
            field=models.CharField(default=generate_salt, max_length=64),
        ),
    ]
