# Generated by Django 3.1.4 on 2021-02-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210220_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[

                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                ('token', models.CharField(max_length=5000)),
                
                ('created_at', models.DateTimeField(auto_now_add=True)),
                # Instead of userID, it's better to use a ForeignKey to link to the Account model
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Account')),
            ],
        ),
    ]
