# Generated by Django 3.1.7 on 2021-03-19 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),  # Reduced max_length to a reasonable size
                ('last_name', models.CharField(max_length=255)),   # Same here
                ('address', models.CharField(max_length=500)),     # Adjusted to a reasonable max_length
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),        # Changed to CharField to properly store phone numbers
                ('email', models.EmailField(max_length=255)),      # Reduced max_length
                ('note', models.CharField(blank=True, max_length=1000)),  # Adjusted to a reasonable limit for notes
                ('address_op', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='token',
            name='user',  # Reverting to the ForeignKey as previously discussed
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Account'),
        ),
    ]
