# Generated by Django 4.2.16 on 2024-10-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_token_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='userID',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
